name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-15"

kv_namespaces = [
    # 注意：将下面的 id 替换为你自己拷贝的 KV 命名空间 id 才能正常使用！
    { binding = "KV_BINDING", id = "8c4e42d0-62e0-49ce-a721-c516ea8c8b4e" },
]

[env.dev]
kv_namespaces = [
    { binding = "KV_BINDING", id = "name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-15"

kv_namespaces = [
    # 注意：将下面的 id 替换为你自己拷贝的 KV 命名空间 id 才能正常使用！
    { binding = "KV_BINDING", id = "8c4e42d0-62e0-49ce-a721-c516ea8c8b4e" },
]

[env.dev]
kv_namespaces = [
    { binding = "KV_BINDING", id = "8c4e42d0-62e0-49ce-a721-c516ea8c8b4e" },
]

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[triggers]
crons = ["0 2 */1 * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true" },
]

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[triggers]
crons = ["0 2 */1 * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
